import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import variables from "./varibles.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next To-do App",
  description: "Generated by create next To-do app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={variables.hero}>
          <Navbar />
          <div className={variables.child}>{children}</div>
        </div>
      </body>
    </html>
  );
}
